# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    csrf_protection:
        enabled: true
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
